-- MySQL Script generated by MySQL Workbench
-- Wed 28 Oct 2015 11:16:12 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dixitdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dixitdb` ;

-- -----------------------------------------------------
-- Schema dixitdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dixitdb` DEFAULT CHARACTER SET latin1 ;
USE `dixitdb` ;

-- -----------------------------------------------------
-- Table `dixitdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`users` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`users` (
  `us_id` INT(11) NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(255) NULL DEFAULT NULL,
  `us_lastname` VARCHAR(255) NULL DEFAULT NULL,
  `us_pseudo` VARCHAR(255) NOT NULL,
  `us_password` VARCHAR(255) NOT NULL,
  `us_avatar` VARCHAR(255) NULL DEFAULT NULL,
  `us_mail` VARCHAR(255) NOT NULL,
  `us_birthdate` DATE NULL DEFAULT NULL,
  `us_signin_date` DATETIME NULL DEFAULT NULL,
  `us_last_connexion` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`decks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`decks` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`decks` (
  `de_id` INT(11) NOT NULL AUTO_INCREMENT,
  `us_id` INT(11) NOT NULL,
  `de_name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `de_status` SMALLINT(6) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`de_id`),
  INDEX `us_id` (`us_id` ASC),
  CONSTRAINT `decks_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`games` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`games` (
  `ga_id` INT(11) NOT NULL AUTO_INCREMENT,
  `de_id` INT(11) NOT NULL,
  `us_id` INT(11) NOT NULL,
  `ga_name` VARCHAR(255) NULL DEFAULT NULL,
  `ga_creation_date` DATETIME NULL DEFAULT NULL,
  `ga_password` VARCHAR(255) NULL DEFAULT NULL,
  `ga_nb_players` INT(11) NOT NULL,
  `ga_points_limit` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`ga_id`),
  INDEX `de_id` (`de_id` ASC),
  INDEX `us_id` (`us_id` ASC),
  CONSTRAINT `games_ibfk_1`
    FOREIGN KEY (`de_id`)
    REFERENCES `dixitdb`.`decks` (`de_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `games_ibfk_2`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`turns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`turns` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`turns` (
  `tu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ga_id` INT(11) NOT NULL,
  `us_id` INT(11) NOT NULL,
  `tu_date_start` DATETIME NULL DEFAULT NULL,
  `tu_date_end` DATETIME NULL DEFAULT NULL,
  `tu_comment` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`tu_id`),
  INDEX `ga_id` (`ga_id` ASC),
  INDEX `us_id` (`us_id` ASC),
  CONSTRAINT `turns_ibfk_3`
    FOREIGN KEY (`ga_id`)
    REFERENCES `dixitdb`.`games` (`ga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `turns_ibfk_4`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`cards` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`cards` (
  `ca_id` INT(11) NOT NULL AUTO_INCREMENT,
  `us_id` INT(11) NOT NULL,
  `ca_name` VARCHAR(255) NULL DEFAULT NULL,
  `ca_image` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`ca_id`),
  INDEX `us_id` (`us_id` ASC),
  CONSTRAINT `cards_ibfk_2`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`boards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`boards` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`boards` (
  `tu_id` INT(11) NOT NULL,
  `ca_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`tu_id`, `ca_id`),
  INDEX `ca_id` (`ca_id` ASC),
  CONSTRAINT `boards_ibfk_1`
    FOREIGN KEY (`tu_id`)
    REFERENCES `dixitdb`.`turns` (`tu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `boards_ibfk_2`
    FOREIGN KEY (`ca_id`)
    REFERENCES `dixitdb`.`cards` (`ca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`cards_decks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`cards_decks` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`cards_decks` (
  `ca_id` INT(11) NOT NULL,
  `de_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`ca_id`, `de_id`),
  INDEX `de_id` (`de_id` ASC),
  CONSTRAINT `cards_decks_ibfk_1`
    FOREIGN KEY (`ca_id`)
    REFERENCES `dixitdb`.`cards` (`ca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cards_decks_ibfk_2`
    FOREIGN KEY (`de_id`)
    REFERENCES `dixitdb`.`decks` (`de_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`chats` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`chats` (
  `us_id` INT(11) NOT NULL,
  `ga_id` INT(11) NOT NULL,
  `ch_text` VARCHAR(255) NOT NULL,
  `ch_date` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  INDEX `us_id` (`us_id` ASC),
  INDEX `ga_id` (`ga_id` ASC),
  CONSTRAINT `chats_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chats_ibfk_2`
    FOREIGN KEY (`ga_id`)
    REFERENCES `dixitdb`.`games` (`ga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dixitdb`.`earned_points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`earned_points` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`earned_points` (
  `us_id` INT(11) NOT NULL,
  `tu_id` INT(11) NOT NULL,
  `points` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`us_id`, `tu_id`),
  INDEX `tu_id` (`tu_id` ASC),
  CONSTRAINT `earned_points_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `earned_points_ibfk_2`
    FOREIGN KEY (`tu_id`)
    REFERENCES `dixitdb`.`turns` (`tu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`errors` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`errors` (
  `er_id` INT(11) NOT NULL AUTO_INCREMENT,
  `er_msg` VARCHAR(255) NOT NULL,
  `er_date` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`er_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`hands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`hands` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`hands` (
  `ca_id` INT(11) NOT NULL,
  `us_id` INT(11) NOT NULL,
  `tu_id` INT(11) NOT NULL,
  `tu_played_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`ca_id`, `us_id`, `tu_id`),
  INDEX `us_id` (`us_id` ASC),
  INDEX `tu_id` (`tu_id` ASC),
  INDEX `tu_played_id` (`tu_played_id` ASC),
  CONSTRAINT `hands_ibfk_3`
    FOREIGN KEY (`ca_id`)
    REFERENCES `dixitdb`.`cards` (`ca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hands_ibfk_4`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hands_ibfk_5`
    FOREIGN KEY (`tu_id`)
    REFERENCES `dixitdb`.`turns` (`tu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hands_ibfk_6`
    FOREIGN KEY (`tu_played_id`)
    REFERENCES `dixitdb`.`turns` (`tu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`messages` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`messages` (
  `me_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `me_text` VARCHAR(255) NULL DEFAULT NULL,
  `me_date` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`me_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`pick`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`pick` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`pick` (
  `ga_id` INT(11) NOT NULL,
  `ca_id` INT(11) NOT NULL,
  `pi_order` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`ga_id`, `ca_id`),
  INDEX `ca_id` (`ca_id` ASC),
  CONSTRAINT `pick_ibfk_1`
    FOREIGN KEY (`ga_id`)
    REFERENCES `dixitdb`.`games` (`ga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pick_ibfk_2`
    FOREIGN KEY (`ca_id`)
    REFERENCES `dixitdb`.`cards` (`ca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`plays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`plays` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`plays` (
  `us_id` INT(11) NOT NULL,
  `ga_id` INT(11) NOT NULL,
  `pl_position` INT(11) NOT NULL,
  `pl_status` ENUM('Attente','Prêt','Inactif') CHARACTER SET 'utf8' NOT NULL DEFAULT 'Attente',
  `pl_last_action` BIGINT(20) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`us_id`, `ga_id`),
  INDEX `ga_id` (`ga_id` ASC),
  CONSTRAINT `plays_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `plays_ibfk_2`
    FOREIGN KEY (`ga_id`)
    REFERENCES `dixitdb`.`games` (`ga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`users_cards_votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`users_cards_votes` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`users_cards_votes` (
  `us_id` INT(11) NOT NULL,
  `ca_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`us_id`, `ca_id`),
  INDEX `ca_id` (`ca_id` ASC),
  CONSTRAINT `users_cards_votes_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `users_cards_votes_ibfk_2`
    FOREIGN KEY (`ca_id`)
    REFERENCES `dixitdb`.`cards` (`ca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Vote pour les cartes ajouté par les joueurs';


-- -----------------------------------------------------
-- Table `dixitdb`.`users_friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`users_friends` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`users_friends` (
  `us_id` INT(11) NOT NULL,
  `us_friend_id` INT(11) NOT NULL,
  `uf_date` DATETIME NOT NULL,
  `uf_status` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`us_id`, `us_friend_id`),
  INDEX `us_friend_id` (`us_friend_id` ASC),
  CONSTRAINT `users_friends_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `users_friends_ibfk_2`
    FOREIGN KEY (`us_friend_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`users_xp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`users_xp` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`users_xp` (
  `us_id` INT(11) NOT NULL,
  `us_xp` INT(11) NOT NULL,
  `ga_id` INT(11) NOT NULL,
  `ga_position` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`us_id`, `ga_id`),
  INDEX `us_id` (`us_id` ASC, `us_xp` ASC, `ga_id` ASC),
  INDEX `ga_id` (`ga_id` ASC),
  CONSTRAINT `users_xp_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `users_xp_ibfk_2`
    FOREIGN KEY (`ga_id`)
    REFERENCES `dixitdb`.`games` (`ga_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dixitdb`.`votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dixitdb`.`votes` ;

CREATE TABLE IF NOT EXISTS `dixitdb`.`votes` (
  `us_id` INT(11) NOT NULL,
  `ca_id` INT(11) NOT NULL,
  `tu_id` INT(11) NOT NULL,
  `vo_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  `updated_at` TIMESTAMP NULL DEFAULT 0000-00-00 00:00:00,
  PRIMARY KEY (`us_id`, `ca_id`, `tu_id`),
  INDEX `ca_id` (`ca_id` ASC),
  INDEX `tu_id` (`tu_id` ASC),
  CONSTRAINT `votes_ibfk_1`
    FOREIGN KEY (`us_id`)
    REFERENCES `dixitdb`.`users` (`us_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `votes_ibfk_2`
    FOREIGN KEY (`ca_id`)
    REFERENCES `dixitdb`.`cards` (`ca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `votes_ibfk_3`
    FOREIGN KEY (`tu_id`)
    REFERENCES `dixitdb`.`turns` (`tu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `dixitdb`;

DELIMITER $$

USE `dixitdb`$$
DROP TRIGGER IF EXISTS `dixitdb`.`before_inset_turns` $$
USE `dixitdb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `dixitdb`.`before_inset_turns`
BEFORE INSERT ON `dixitdb`.`turns`
FOR EACH ROW
BEGIN
	DECLARE oldTurnComment VARCHAR(255);
	SELECT tu_comment INTO oldTurnComment
	FROM turns
	WHERE ga_id = NEW.ga_id
	ORDER BY tu_id DESC
	LIMIT 1;
	IF oldTurnComment = "" THEN
		INSERT INTO errors(er_msg, er_date) VALUES('ERR_TURN', NOW());
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
